### ISSUE TITLE
use throttler on tasks without provide the total task..

### ISSUE THREAD

**Issue by xCoderly** [nozzle/throttler#13]
Hi,

is it possible to have another function like this one `New(2, len(urls))` without providing the number of tasks in total?

https://github.com/nozzle/throttler/blob/2ea982251481626167b7f83be1434b5c42540c1a/example_test.go#L21

Thanks.

**Comment by josephbergevin** [comment]
Not really as written. That number `len(urls)` is what is used to tell Throttler when to stop blocking. I'm curious what your use-case would be for this request, though. Can you give me more information or a code sample?

**Comment by xCoderly** [comment]
i already built my own Throttler based on waitgroup, its just a workaround, i will share my way when i can..

Thanks for your reply.

**Comment by xCoderly** [comment]
Sorry for the late reply,

i tried the first implementation using to a custom waiting group that have just a count() function this is what i use normally on my projects, and i add one on another one as normal waiting group and the second as a throttler when done() called on the throttler he triger done() on the main waiting grop if not nill, and when count() of trothler hit the max number he block until he get a sign on channel but it block forever somehow, so i changed the concept and use a simpler way 

this is an example : 

	
	var (
		aMaxRequests = 1000
		RThrottler   = &Throttler{}
	)
	
	func main(){
	
		RThrottler = NewThrottler(aMaxRequests)
	
		aWGProcess := &AWaitingGroup{}
		aWGProcess.Throttler = RThrottler

		for _, PassedData := range FullData {

			aWGProcess.Throttler.Throttle()

			aWGProcess.Add(1)
			go DoWork(*PassedData, aWGProcess)

		}

		aWGProcess.Wait()
	
	}
	

and it worked for me now,

this solution is based on this https://github.com/zenthangplus/goccm but i faced some issue so i make it work as i wanted..

**Comment by xCoderly** [comment]
my use case is that i have multiple Launcher for example

City 1
City 2 
City 3

every city i call a CityProcesser() that launches a lot of goroutine for action on that specific city, and all those cities CityProcesser() execute on parallel so every CityProcesser before i launch any task on that city i should check if i hit the requests limit or not if i hit it, he will block until some task finished..

so before launching any task, i execute the Throttle() function that block if the limit hit so if the limit hit all CityProcesser will block until some task finished and launched another one, so this limit the number fo tasks executed in the same time even i have multiple task launcher.

i hope you get my idea.
