### ISSUE TITLE
Calling function between batches?

### ISSUE THREAD

**Issue by kmatt** [nozzle/throttler#3]
Will the BatchedThrottler function allow grouping of jobs in batches and calling a function between those batches?

For example if I have 10 files, and want to process them in groups of 4 concurrently but call an aggregation function after files 4, 8, and 10.

**Comment by derekperkins** [comment]
@kmatt Sorry we missed seeing this issue. You shouldn't have to make any changes to throttler to make this work how you expect. If you set `batchSize = 4`, then you would just call your function right before calling `th.Throttle` in your loop.
