### ISSUE TITLE
Changing the number of workers dynamically

### ISSUE THREAD

**Issue by zboralski** [nozzle/throttler#4]
Do you see any issues with exporting maxWorkers? 

I'd to adjust the number of workers after t.Throttle() based on some metrics.

**Comment by josephbergevin** [comment]
Interesting. I think that'd be fine, but rather than exporting `maxWorkers`, I would set it through a method off Throttler (`th.SetMaxWorkers(int)`). 

Any chance you could Fork it and submit a PR for this request?

**Comment by zboralski** [comment]
I already forked and did exactly that :)

Do you prefer to panic or simply do nothing if maxworkers is less than 1?

```go
// SetMaxWorker allows you to change the maximum number of workers dynamically
// after Throttle is called. It will do nothing if maxWorkers < 1.
func (t *Throttler) SetMaxWorker(maxWorkers int) {
	if maxWorkers > 0 {
		t.maxWorkers = maxWorkers
	}
}
```
or

```go
// SetMaxWorker allows you to change the maximum number of workers dynamically
// after Throttle is called. It panics if maxWorkers < 1.
func (t *Throttler) SetMaxWorker(maxWorkers int) {
	if maxWorkers < 1 {
		panic("maxWorkers has to be at least 1")
	}
        t.maxWorkers = maxWorkers
}
```

**Comment by derekperkins** [comment]
I would prefer to panic.

I think you'll also need to add a mutex to throttler to avoid race conditions when setting maxWorkers.

**Comment by derekperkins** [comment]
@zboralski Thanks for the suggestion, it's now a part of the main library. There have been a number of other changes, including eliminating a few data races, so I'd definitely use the upstream / update your fork if you can. Sorry it took so long to get implemented.
