### ISSUE TITLE
Data Race

### ISSUE THREAD

**Issue by peking2** [nozzle/throttler#6]
WARNING: DATA RACE
Read at 0x00c42054c3e0 by goroutine 42:
  code.uber.internal/driver/fleet_finance/vendor/github.com/nozzle/throttler.(*Throttler).Throttle()
      /mnt/jenkins/workspace/test-fleet_finance/.tmp/.goroot/src/code.uber.internal/driver/fleet_finance/vendor/github.com/nozzle/throttler/throttler.go:84 +0x1e3

Previous write at 0x00c42054c3e0 by goroutine 43:
  code.uber.internal/driver/fleet_finance/vendor/github.com/nozzle/throttler.(*Throttler).Done()
      /mnt/jenkins/workspace/test-fleet_finance/.tmp/.goroot/src/code.uber.internal/driver/fleet_finance/vendor/github.com/nozzle/throttler/throttler.go:95 +0x1c8
  
func (t *Throttler) Done(err error) {
	t.doneChan <- struct{}{}
	if err != nil {
		t.errsMutex.Lock()
		t.errs = append(t.errs, err)
		t.errorCount++
		t.errsMutex.Unlock()
	}
}

Should t.doneChan <- struct{}{} after if err != nil?

**Comment by derekperkins** [comment]
Yes, I think you're right. I've contemplated switching out that count var for an atomic int, but haven't had a need to do that yet. Maybe now is as good a time as any. :)

**Comment by derekperkins** [comment]
@peking2 Thanks for reporting that. I just submitted a PR to fix that data race. I may loop back through here and revisit some atomic values at some point, but this should be good for now.

**Comment by peking2** [comment]
@derekperkins thanks for a quick fix. :)

**Comment by derekperkins** [comment]
@peking2 I fixed a few other places that might have triggered a similar warning for you and released a new version.
